In [1]:
import torch

In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-10, -15, -68,   0, -78, -30])

In [4]:
tensor = torch.tensor([[0.1, 0.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 0.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [7]:
probabilities = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probabilities, num_samples = 20, replacement=True)
print(samples)

tensor([1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1])


In [11]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [13]:
out = torch.tril(torch.ones(5,5))  #lower triangle
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [14]:
out = torch.triu(torch.ones(5,5))  #lower triangle
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [15]:
torch.stack([out, samples, tensor]) # for stacking equal size 
torch

RuntimeError: stack expects each tensor to be equal size, but got [5, 5] at entry 0 and [20] at entry 1

In [17]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear  = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ 5.7191,  2.8202, -6.7297], grad_fn=<SqueezeBackward4>)


In [19]:
import torch.nn.functional as f

tensor1 = torch.tensor([1.,2.,3.])
softmax_output = f.softmax(tensor1, dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [20]:
#initialize an embedding layer

vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# create some input indicies
input = torch.LongTensor([1,5,2,3])

embedding_output = embedding(input)

print(embedding_output.shape)
print(embedding_output)

torch.Size([4, 6])
tensor([[ 1.3293, -0.7706,  1.0245, -0.3952,  0.2234,  0.7865],
        [ 1.5168, -0.9921,  0.3130, -0.3492, -0.6305, -0.6410],
        [-0.3139, -1.5202, -0.1906, -0.7495, -0.4985, -0.3873],
        [-0.3978, -0.4799,  2.0210, -1.3432,  0.2555, -1.3444]],
       grad_fn=<EmbeddingBackward0>)


In [24]:
a = torch.tensor([[1,2], [3,4], [5,6]])
b = torch.tensor([[7,8,9], [10,11, 12]])
print(a @ b)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [25]:
from torch.nn import functional as F

In [ ]:
class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size, )